TEST = data/processed/test.csv
TRAIN = data/processed/train.csv
VAL = data/processed/val.csv

data: $(TEST) $(TRAIN) $(VAL)
	# DOWNLOAD THAT DATA THOUGH
	say "I haven't made this script yet"

plots: data
	say "I can't make plots without data"

test: data
	python test.py
